Update @orb.yml

diff --git a/src/@orb.yml b/src/@orb.yml
--- a/src/@orb.yml
+++ b/src/@orb.yml
@@ -185,10 +185,11 @@ jobs:
                 curl -d '{ "body": "'"${BODY}"'" }' -X POST "${GITHUB_URL}"
               } &> /dev/null
 
-    - run:
-        name: Report
-        command: |
-          if [ -f "backstop_failed.txt" ] ; then
-            echo "Backstop report failed."
-            exit 1
-          fi
+# Trying CircleCI manual approval instead of automatic failure https://circleci.com/docs/2.0/workflows/#holding-a-workflow-for-a-manual-approval
+#    - run:
+#        name: Report
+#        command: |
+#          if [ -f "backstop_failed.txt" ] ; then
+#            echo "Backstop report failed."
+#            exit 1
+#          fi
